name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -o rift-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o rift-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -o rift-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o rift-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -o rift-windows-amd64.exe .
        
        # Create archives
        tar -czf rift-linux-amd64.tar.gz rift-linux-amd64
        tar -czf rift-linux-arm64.tar.gz rift-linux-arm64
        tar -czf rift-darwin-amd64.tar.gz rift-darwin-amd64
        tar -czf rift-darwin-arm64.tar.gz rift-darwin-arm64
        zip rift-windows-amd64.zip rift-windows-amd64.exe
        
        # Calculate SHA256 hashes
        echo "## SHA256 Checksums" >> checksums.txt
        sha256sum rift-*.tar.gz rift-*.zip >> checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rift-linux-amd64.tar.gz
          rift-linux-arm64.tar.gz
          rift-darwin-amd64.tar.gz
          rift-darwin-arm64.tar.gz
          rift-windows-amd64.zip
          checksums.txt
        generate_release_notes: true
        
    - name: Update Homebrew Formula
      if: github.repository == 'jacksmethurst/rift-cli'
      run: |
        # Get SHA256 hashes for macOS binaries
        DARWIN_AMD64_SHA=$(sha256sum rift-darwin-amd64.tar.gz | cut -d' ' -f1)
        DARWIN_ARM64_SHA=$(sha256sum rift-darwin-arm64.tar.gz | cut -d' ' -f1)
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Clone and update homebrew tap repository
        git clone https://${{ secrets.HOMEBREW_PAT }}@github.com/jacksmethurst/homebrew-rift-cli.git
        cd homebrew-rift-cli
        
        # Update formula
        cat > Formula/rift.rb << EOF
        class Rift < Formula
          desc "A Git alternative written in Go"
          homepage "https://github.com/jacksmethurst/rift-cli"
          version "$VERSION"

          on_macos do
            if Hardware::CPU.intel?
              url "https://github.com/jacksmethurst/rift-cli/releases/download/v$VERSION/rift-darwin-amd64.tar.gz"
              sha256 "$DARWIN_AMD64_SHA"
            end
            if Hardware::CPU.arm?
              url "https://github.com/jacksmethurst/rift-cli/releases/download/v$VERSION/rift-darwin-arm64.tar.gz"
              sha256 "$DARWIN_ARM64_SHA"
            end
          end

          def install
            bin.install "rift-darwin-amd64" => "rift" if Hardware::CPU.intel?
            bin.install "rift-darwin-arm64" => "rift" if Hardware::CPU.arm?
          end

          test do
            system "#{bin}/rift", "version"
          end
        end
        EOF
        
        # Commit and push to homebrew tap
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Formula/rift.rb
        git commit -m "Update rift formula to v$VERSION"
        git push origin main